# Generated by Django 5.2.4 on 2025-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('image_muscles', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('good', 'Хорошее'), ('repair', 'Требует ремонта')], default='good', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='services_images/')),
                ('slag', models.CharField(max_length=50)),
            ],
        ),
    ]
